extends Node

const GAME_SET_START_TIME = "GAME_SET_START_TIME"
const GAME_SET_STATE = "GAME_SET_STATE"

const PLAYER_SET_ACTION_QUEUE = "PLAYER_SET_ACTION_QUEUE"
const PLAYER_SET_HEALTH = "PLAYER_SET_HEALTH"
const PLAYER_SET_POSITION = "PLAYER_SET_POSITION"
