extends Node

const CLIENT_SET_STATE = "CLIENT_SET_STATE"
const CLIENT_SET_MAP = "CLIENT_SET_MAP"

const GAME_SET_START_TIME = "GAME_SET_START_TIME"
const GAME_SET_STATE = "GAME_SET_STATE"

const PLAYER_ADD_PLAYER = "PLAYER_ADD_PLAYER"
const PLAYER_SET_ACTION_QUEUE = "PLAYER_SET_ACTION_QUEUE"
const PLAYER_SET_HEALTH = "PLAYER_SET_HEALTH"
const PLAYER_SET_POSITION = "PLAYER_SET_POSITION"
const PLAYER_SET_READY = "PLAYER_SET_READY"
